# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('uploadId', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
    ]
