# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfm_music', '0004_auto_20170407_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='netease',
            name='artist',
            field=models.CharField(default='OK', max_length=100),
        ),
    ]
