# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfm_music', '0005_netease_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netease',
            name='artist',
            field=models.CharField(max_length=100),
        ),
    ]
