# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('heat', models.IntegerField()),
                ('lastlogindate', models.DateField(auto_now=True)),
            ],
        ),
    ]
